sudo: required
dist: trusty

language: node_js
node_js: 8
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  - haxe lix.client.hxml
  - haxe haxeshim.hxml
  
script:
  - lix run travix neko